version: "3"
services:

  mongo-express:
    container_name: "mongo-express"
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: EXroot
      ME_CONFIG_BASICAUTH_PASSWORD: EXpassword
      ME_CONFIG_MONGODB_SERVER: mongodb-container
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: projectdb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    links:
      - mongodb
    networks:
      - mongo-compose-network

  mongodb:
    container_name: "mongodb-container"
    image: mongo:3.6
    ports:
        - "27017:27017"
    environment:
        MONGO_INITDB_DATABASE: projectdb
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
    restart: always
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
