version: "3"
services:

  mongodb:
    container_name: "mongodb-container"
    image: mongo:3.6
    ports:
        - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
    restart: always
